[package]
name = "insta"
version = "1.0.0"
license = "Apache-2.0"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
description = "A snapshot testing library for Rust"
edition = "2018"
homepage = "https://github.com/mitsuhiko/insta"
repository = "https://github.com/mitsuhiko/insta"
keywords = ["snapshot", "testing", "jest", "approval"]
readme = "README.md"
exclude = [
    "assets/*"
]

[package.metadata.docs.rs]
all-features = true

[features]
default = []

# when the redactions feature is enabled values can be redacted in serialized
# snapshots.
redactions = ["pest", "pest_derive"]

# Glob support
glob = ["globwalk"]

# This feature is now just always enabled because we use yaml internally now.
serialization = []

[dependencies]
csv = { version = "1.1.3", optional = true }
difference = "2.0.0"
serde = { version = "1.0.85", features = ["derive"] }
serde_yaml = "0.8.8"
console = { version = "0.12.0", default-features = false }
serde_json = "1.0.36"
lazy_static = "1.4.0"
pest = { version = "2.1.0", optional = true }
pest_derive = { version = "2.1.0", optional = true }
ron = { version = "0.6.2", optional = true }
backtrace = { version = "0.3.42", optional = true }
globwalk = { version = "0.8.0", optional = true }
toml = { version = "0.5.6", optional = true }
